name: RSpec

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # build:
  #   strategy:
  #     matrix:
  #       os: [macos-latest, ubuntu-latest]
  #       ruby: [2.6, 2.7]
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions-rs/toolchain@v1
  #     with:
  #       toolchain: stable
  #   - uses: ruby/setup-ruby@v1
  #     with:
  #       ruby-version: ${{ matrix.ruby }}
  #       bundler-cache: true
  #   - run: bundle exec rake --version
  #   - run: bundle exec rake default
  # build-win:
  #   strategy:
  #     matrix:
  #       ruby:
  #         # - 2.6
  #         # - 2.7
  #         # - mingw
  #         - mswin
  #   runs-on: windows-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions-rs/toolchain@v1
  #     with:
  #       toolchain: stable
  #   - uses: ruby/setup-ruby@v1
  #     with:
  #       ruby-version: ${{ matrix.ruby }}
  #   - run: bundle install
  #   - run: rake
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: MSP-Greg/setup-ruby-pkgs@v1
      with:
        brew: true
    - run: bundle install
    - run: rake
